server:
  port: "8080"
  mode: "debug" # gin 运行模式: debug, release, test

database:
  driver: "postgres"
  host: "localhost"
  port: "5432"
  user: "TJY"        # 数据库用户名
  password: "123456" # 数据库密码
  dbname: "goDB"       # 数据库名
  sslmode: "disable"
  timezone: "Asia/Shanghai"
  #dsn:"data.db"
  MaxIdleConns: 10
  MaxOpenConns: 100
  ConnMaxLifetime : 1h

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

auth:
  token_expire_hours: 24h

cors:
  allow_origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"

ratelimit:
  global_limit: 15
  ip_limit: 3